### PR TITLE
Storing and applying last known vertical scroll

### PR DESCRIPTION
**Pull request by surajhell88**
Change request for the issue specified in https://github.com/phuoc-ng/html-dom/issues/137
Ability to store vertical scroll position in a variable on every location change. 
Then applying for that scroll position whenever User returns to index route from a post route.

### CODE REVIEW

**Comment by phuoc-ng** [comment]
That looks good. Thanks @surajhell88

**Comment by phuoc-ng** [comment]
@surajhell88 The PR is merged and deployed. But the [live site](https://htmldom.dev/) doesn't work as expectation.
Will need to revisit it.

**Comment by surajhell88** [comment]
> live site



> @surajhell88 The PR is merged and deployed. But the [live site](https://htmldom.dev/) doesn't work as expectation.
> Will need to revisit it.

@phuoc-ng Hey I am so sorry, I just sort of tested it on chrome and brave, it works fine on them. There is some issue with firefox I sort of tested it now. I will work towards solving that and push in another PR. Also if you found the issue on Chrome/Brave too, do let me know.

**Comment by phuoc-ng** [comment]
Thank @surajhell88.

My expected behavior is that:
* Access the home page, scroll to given post
* Click on post, and then click on the header to go to the home page
* It should scroll to the last post position

Is this correct?

**Comment by surajhell88** [comment]
Oops, I just checked it on the back button given in the browser. Never checked it when on click of the header. I will work on this now as well as the firefox issue as well.

**Pull request merged**
